[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
buildContext = "backend"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
