name: Deploy Frontend to Firebase Hosting

on:
  push:
    branches: [ main ]
    paths: 
      - 'frontend/**'
      - '.github/workflows/deploy-frontend.yml'
  workflow_dispatch: # Allow manual trigger

env:
  NODE_VERSION: '20'

jobs:
  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Create production environment file
        working-directory: ./frontend
        run: |
          cat > .env.production << EOF
          # Production Environment Variables for Firebase Hosting
          NEXT_PUBLIC_SUPABASE_URL=https://ldhpaziilslunjcdhmpl.supabase.co
          NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkaHBhemlpbHNsdW5qY2RobXBsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMDEzNzQsImV4cCI6MjA3MDc3NzM3NH0.abeFIWQ96-HDIjMwYJI-HC6EDgp9q2q6lzaVnUeN98E

          # Backend configuration - using Cloud Run URL directly since proxy isn't working  
          NEXT_PUBLIC_BACKEND_MODE=production
          NEXT_PUBLIC_BACKEND_URL=https://scra-backend-xnsgnxzzsa-uc.a.run.app

          # Site URL for OAuth redirects
          NEXT_PUBLIC_SITE_URL=https://scra-b341a.web.app/
          EOF

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SCRA_B341A }}'
          projectId: scra-b341a
          entryPoint: './frontend'